title:  標準吳語輸入法
logo: assets/logo.jpg
show_downloads: true
theme: jekyll-theme-minimal
github:
  zip_url: https://github.com/saeziae/rime_nguphing/releases/latest
  tar_url: https://github.com/saeziae/rime_nguphing/releases/latest