name: 新增單字
description: 新增單字發音
labels: ["new-char"]
body:
  - type: input
    id: char
    attributes:
      label: 漢字
    validations:
      required: true
  - type: input
    id: phing-in
    attributes:
      label: 拼音
    validations:
      required: true
  - type: textarea
    id: caveats
    attributes:
      label: 其他說明
