name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: packing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run deployment script
        run: bash scripts/pack-trime.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nguphing-datapack-${{ github.run_id }}
          path: build/*
